### PR TITLE
OC dialog related css changes

### PR DESCRIPTION
**Pull request by TSI-kavitasonawane**
This PR contain OC dialog core app related CSS changes and file_zip related CSS changes.

### CODE REVIEW

**Comment by tsdicloud** [comment]
Please describe why this change is needed and what it changes compared to standard.

**Comment by tsdicloud** [comment]
Please describe why this change is needed and what it changes compared to standard.

**Comment by TSI-kavitasonawane** [comment]
Changes included -
**OC dialog changes:**

1. Spacing and alignment modified for dialog box
2. Icons and text hover effect to magenta
3. Close button icon changed.
4. Modified background color for OC dialog buttons with magenta.

**Comment by tsdicloud** [comment]
Hardcoded colors
Still invalid unset function used

**Pull request closed without merging**
