### PR TITLE
updated header search option customization

### PR DESCRIPTION
**Pull request by TSI-nareshrai**
Added styling & js changes for header search component

### CODE REVIEW

**Comment by tsdicloud** [comment]
customutils is a wild mixture of Taelium and other code and should be removed.

The Taelium part should move to Mac_marketing as an independent unit that
is enabled together with marketing app.

The other utils should either go where the are actually used or at least go into a separate, functional branch.

**Comment by tsdicloud** [comment]
Please focus first on a simple theming with variables. Would be helpful to keep "basic sass" theming working without any functional changes as independent testable unit.

We wanted to focus only on a first iteration where we set all variables. Why is it not really reflected in the branches I see?

**Comment by tsdicloud** [comment]
'default.php' could become a bottleneck file for merging. Recommendation to make it part of the basic theming branch and only change it there.

**Comment by TSI-nareshrai** [comment]
> 'default.php' could become a bottleneck file for merging. Recommendation to make it part of the basic theming branch and only change it there.


but if we are creating js file in this branch then we should include this in default .php in same branch..
how could i will keep default.php file change in other branch ??

**Comment by TSI-nareshrai** [comment]
it will be very difficult  while working on local on specific branch, which doest have styling changes but only template change..
how could we see all feature together on local.

**Comment by tsdicloud** [comment]
You will see all features combined if you have all the branches for a feature merged.

For testing, you pick the branches you need for complete functionality and merge them into pure NC package - should be easy git task for a developer. On final CI build, all branches are merged anyway - except you break a centrally needed branch. Remember the difference between logical and file-merge dependencies.

In case of a file that contains a kind of "registration" for all other changes, this is a bottleneck and will constantly merge-fail if branches are applied in random order. So, to make it mergeable, the pragmatic way is to keep it in one branch - in his case the basic theme. iF you know a better way to keep the changed spread over multiple branches - share the design please. We found no way so far.

I would strongly recommend to not experiemnt with the new delivery model to "bend" it for your expectations, but learn to orchestrate the concept properly.

**Pull request closed without merging**
