### PR TITLE
Files app breadcrumb

### PR DESCRIPTION
**Pull request by TSI-nareshrai**
added breadcrumb related JS & styling

### CODE REVIEW

**Comment by tsdicloud** [comment]
Please describe why this change is needed and what it changes compared to standard.

**Comment by TSI-nareshrai** [comment]
Changes included - 
1. Icons and text hover effect to magenta 
2. Share icon removed 
3. Spacing and Alignment modified
4. Add label added through JS file as not able to update in Vue template. and this changes is not there in NC

**Comment by tsdicloud** [comment]
Please use theme general settings variables, not fixed color var(--magenta-color);

**Comment by tsdicloud** [comment]
Multiple time hardcoded magenta, usage of forbidden unset function.
Strange design of .js file with a single function and no package/namespace isolation.

**Pull request closed without merging**
