### PR TITLE
Filelist and Toggle view changes

### PR DESCRIPTION
**Pull request by TSI-kavitasonawane**
Filelist View and Grid View changes

### CODE REVIEW

**Comment by tsdicloud** [comment]
We are removing gridwiev completely, so why do we have grid view changes?

**Comment by tsdicloud** [comment]
Please describe why this change is needed and what it changes compared to standard.

**Comment by TSI-kavitasonawane** [comment]
> We are removing gridwiev completely, so why do we have grid view changes?

Sorry, this PR does not contain grid view changes its contain fileList toggle view changes.  I am going to update branch name as well.

**Comment by TSI-kavitasonawane** [comment]
> Please describe why this change is needed and what it changes compared to standard.

**This PR contain following changes:**

- File list view changes
- File list toggle view changes
- Updated thumbnail width and height
- Mimetype icons changes
- Spacing and Alignment modified for fileList table.
- Icons and text hover effect to magenta
- Icons changes
- Table,td,tr alignment modified.

**Comment by tsdicloud** [comment]
But althrough the stylesheet, there are references to view grid like:

```
.files-filestable:not(.view-grid) tbody tr:active,
.files-filestable:not(.view-grid) tbody tr:hover,
.files-filestable:not(.view-grid) tbody tr:focus,
.files-filestable:not(.view-grid) tbody tr.highlighted,
.files-filestable:not(.view-grid) tbody tr.highlighted .name:focus,
.files-filestable:not(.view-grid) tbody tr.selected,
.files-filestable:not(.view-grid) tbody tr.searchresult {
	background-color: rgb(242 242 242 / 50%) !important;
}
```

**Comment by TSI-kavitasonawane** [comment]
> But althrough the stylesheet, there are references to view grid like:
> 
> ```
> .files-filestable:not(.view-grid) tbody tr:active,
> .files-filestable:not(.view-grid) tbody tr:hover,
> .files-filestable:not(.view-grid) tbody tr:focus,
> .files-filestable:not(.view-grid) tbody tr.highlighted,
> .files-filestable:not(.view-grid) tbody tr.highlighted .name:focus,
> .files-filestable:not(.view-grid) tbody tr.selected,
> .files-filestable:not(.view-grid) tbody tr.searchresult {
> 	background-color: rgb(242 242 242 / 50%) !important;
> }
> ```

Yes but for Toggle view Nextcloud added class name view-grid for table. So we have added this CSS. 
Added screenshot for your reference.
toggleview

**Comment by tsdicloud** [comment]
Hardcoded colors (e.g. #73C354), forbidden unset function, braking Nextcloud standard
Needs complete redoing.

**Pull request closed without merging**
